name: CI test unit
on: 
  workflow_dispatch:
  push:
  schedule:
    # Exécute tous les jours à minuit UTC
    - cron: '0 0 * * 1-5'

jobs:
    unit-test-job:
      name: unit test job
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v7

        - name: setup nodeJs
          uses: actions/setup-node@v7

        - name: install dependencies
          run: npm install

        - name: install mocha junit reporter
          run: npm install --save-dev mocha-junit-reporter

        - name: run node tes
          run: npm run test

        - name: run mocha report
          run: npx mocha --reporter mocha-junit-reporter
          env:
              MOCHA_FILE: ./junit-report.xml

        - uses: actions/upload-artifact@v7
          with:
            name: mocha-report.txt
            path: ./junit-report.xml
          


      